
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "node_screenshots"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0", default-features = false, features = ["napi4"] }
napi-derive = "3.0.0"
xcap = { path = "../xcap", features = ["image"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
