/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Screenshots {
  id: number
  x: number
  y: number
  width: number
  height: number
  rotation: number
  scaleFactor: number
  isPrimary: boolean
  static all(): Array<Screenshots>
  static fromPoint(x: number, y: number): Screenshots | null
  captureSync(copyOutputData?: boolean | undefined | null): Buffer
  capture(copyOutputData?: boolean | undefined | null): Promise<Buffer>
  captureAreaSync(x: number, y: number, width: number, height: number, copyOutputData?: boolean | undefined | null): Buffer
  captureArea(x: number, y: number, width: number, height: number, copyOutputData?: boolean | undefined | null): Promise<Buffer>
}
