/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Monitor {
  /** Unique identifier associated with the screen. */
  readonly id: number
  /** Unique identifier associated with the screen. */
  readonly name: string
  /** The screen x coordinate. */
  readonly x: number
  /** The screen x coordinate. */
  readonly y: number
  /** The screen pixel width. */
  readonly width: number
  /** The screen pixel height. */
  readonly height: number
  /** Can be 0, 90, 180, 270, represents screen rotation in clock-wise degrees. */
  readonly rotation: number
  /** Output device's pixel scale factor. */
  readonly scaleFactor: number
  /** The screen refresh rate. */
  readonly frequency: number
  /** Whether the screen is the main screen */
  readonly isPrimary: boolean
  static all(): Array<Monitor>
  static fromPoint(x: number, y: number): Monitor | null
  captureImageSync(copyOutputData?: boolean | undefined | null): Buffer
  captureImage(copyOutputData?: boolean | undefined | null): Promise<Buffer>
}
export class Window {
  /** The window id */
  readonly id: number
  /** The window app name */
  readonly appName: string
  /** The window title */
  readonly title: string
  /** The window current monitor */
  readonly currentMonitor: Monitor
  /** The window x coordinate. */
  readonly x: number
  /** The window x coordinate. */
  readonly y: number
  /** The window pixel width. */
  readonly width: number
  /** The window pixel height. */
  readonly height: number
  /** The window is minimized. */
  readonly isMinimized: boolean
  /** The window is maximized. */
  readonly isMaximized: boolean
  static all(): Array<Window>
  captureImageSync(copyOutputData?: boolean | undefined | null): Buffer
  captureImage(copyOutputData?: boolean | undefined | null): Promise<Buffer>
}
