name: Lint

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        host:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    name: Lint on ${{ matrix.host }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies
        if: ${{ matrix.host == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libclang-dev libxcb1-dev libxrandr-dev libdbus-1-dev libpipewire-0.3-dev

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy
